version: '3.7'

services:
  main:
    container_name: iotfreezer-backend
    build:
      context: .
    ports:
      - ${DOCKER_MAPPED_PORT}:${SERVER_PORT}
    command: yarn run start
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      # - postgrestest
      - postgres
      - mosquitto
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
  postgres:
    container_name: iotfreezer-postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    expose:
      - ${TYPEORM_PORT} # Publishes 5433 to other containers but NOT to host machine
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    command: -p ${TYPEORM_PORT}
  # postgrestest:
  #   container_name: postgrestest
  #   image: postgres:12
  #   networks:
  #     - webnet
  #   environment:
  #     POSTGRES_PASSWORD: ${PGPASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_DATABASE}
  #   ports:
  #     - 5433:5432
  #   logging:
  #     driver: "json-file"
  #     options:
  #         max-file: "5"
  #         max-size: "10m"
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    networks:
      - webnet
networks:
  webnet:
volumes:
  pgdata:
