version: '3.7'

services:
  backend:
    container_name: iotfreezer-backend
    profiles:
      - run
    build:
      context: .
    ports:
      - "127.0.0.1:${DOCKER_MAPPED_PORT}:${SERVER_PORT}"
    command: yarn run start
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
  postgres:
    container_name: iotfreezer-postgres
    profiles:
      - run
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    expose:
      - ${TYPEORM_PORT} # Publishes 5433 to other containers but NOT to host machine
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    command: -p ${TYPEORM_PORT}
  mosquitto:
    container_name: iotfreezer-mosquitto
    profiles:
      - run
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
    networks:
      - webnet
  backendtest:
    container_name: iotfreezer-backend-test
    profiles:
      - testing
    build:
      context: .
    ports:
      - "127.0.0.1:${DOCKER_MAPPED_PORT_TEST}:${SERVER_PORT}"
    command: bash -c 'while !</dev/tcp/postgrestest/${TYPEORM_PORT}; do sleep 1; done; yarn run test'
    env_file:
      - .env.test
    networks:
      - webnet
    depends_on:
      - postgrestest
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
  postgrestest:
    container_name: postgrestest
    profiles:
      - testing
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    expose:
      - ${TYPEORM_PORT} # Publishes 5433 to other containers but NOT to host machine
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    command: -p ${TYPEORM_PORT}
networks:
  webnet:
volumes:
  pgdata:
